-- FIRST: Create the audit table if it doesn't exist
CREATE TABLE audit_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50),
    operation VARCHAR2(10),  -- INSERT, UPDATE, DELETE
    record_id VARCHAR2(100),
    changed_by VARCHAR2(100),
    changed_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    description VARCHAR2(500)
);

-- 1. VIEW ALL AUDIT RECORDS
SELECT 
    table_name,
    operation,
    changed_by,
    TO_CHAR(changed_date, 'DD-MON HH24:MI') as time,
    description
FROM audit_log
ORDER BY changed_date DESC;

-- 2. VIEW USER ACTIVITY
SELECT 
    changed_by,
    COUNT(*) as total_actions,
    SUM(CASE WHEN operation = 'INSERT' THEN 1 ELSE 0 END) as inserts,
    SUM(CASE WHEN operation = 'UPDATE' THEN 1 ELSE 0 END) as updates,
    SUM(CASE WHEN operation = 'DELETE' THEN 1 ELSE 0 END) as deletes
FROM audit_log
GROUP BY changed_by;

-- 3. VIEW TODAY'S ACTIVITY
SELECT 
    operation,
    table_name,
    changed_by,
    description
FROM audit_log
WHERE TRUNC(changed_date) = TRUNC(SYSDATE)
ORDER BY changed_date DESC;

-- 4. VIEW SUSPICIOUS ACTIVITY (multiple deletes)
SELECT changed_by, COUNT(*) as delete_count
FROM audit_log
WHERE operation = 'DELETE'
  AND changed_date > SYSDATE - 1  -- Last 24 hours
GROUP BY changed_by
HAVING COUNT(*) > 3;
